name: Clojure CI

on: [push]

jobs:
  env:
    DB_PORT: ${{ job.services.couchbase.ports['8091'] }}
 
  build:
    
    runs-on: ubuntu-latest
    services:
      couchbase:
        image: docker.io/fhitchen/clj-cb-testdb
        ports:
          - 8091/tcp
          - 11210/tcp
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: lein deps
      - name: Run tests
        run: lein test :only earthen.clj-cb.cluster-test
#       run: lein test :only earthen.clj-cb.bucket-test/prepared-statement
#    container:
#      image: docker.io/fhitchen/clj-cb-testdb
#      ports:
#        - 8091-8094:8091-8094
#        - 11210:11210
#      options: --entrypoint /configure.sh

